// Prato da Semana — base de dados de receitas
// Fotos: TheMealDB (https://www.themealdb.com) — imagens reais dos pratos.
// Preços: estimativa por dose (€), para Portugal. Alergénios e lojas curados manualmente.

window.ALLERGENS = [
  { id: "lactose",   label: "Lactose / Laticínios", emoji: "🥛" },
  { id: "gluten",    label: "Glúten",               emoji: "🌾" },
  { id: "ovo",       label: "Ovo",                  emoji: "🥚" },
  { id: "amendoim",  label: "Amendoim",             emoji: "🥜" },
  { id: "frutosSecos", label: "Frutos secos",       emoji: "🌰" },
  { id: "peixe",     label: "Peixe",                emoji: "🐟" },
  { id: "marisco",   label: "Marisco",              emoji: "🦐" },
  { id: "soja",      label: "Soja",                 emoji: "🫘" },
  { id: "sesamo",    label: "Sésamo",               emoji: "🌱" },
];

window.STORES = [
  { id: "continente", label: "Continente", cor: "#D50032", logo: "icons/store-continente.svg" },
  { id: "pingoDoce",  label: "Pingo Doce",  cor: "#ED1C24", logo: "icons/store-pingodoce.png" },
  { id: "mercadona",  label: "Mercadona",   cor: "#00834D", logo: "icons/store-mercadona.svg" },
];

// Alimentos que o utilizador pode evitar — atalhos rápidos + lista completa.
window.AVOID_PRESETS = [
  "cogumelos", "coentros", "alho", "cebola",
  "malagueta", "azeitonas", "queijo", "ovos",
];

window.AVOIDABLE_FOODS = [
  // Hortícolas & cogumelos
  "abóbora", "alface", "alho", "alho-francês", "azeitonas", "batata-doce", "batatas",
  "beringela", "brócolos", "cenoura", "cebola", "cogumelos", "couve", "curgete",
  "ervilhas", "espargos", "espinafres", "feijão-verde", "funcho", "milho", "pepino",
  "pimento", "pimentos", "rúcula", "tomate", "tomate-cereja",
  // Frutas
  "abacate", "ananás", "banana", "framboesas", "limão", "maçã", "morangos",
  "pêssego", "uva",
  // Leguminosas & cereais
  "arroz", "aveia", "cuscuz", "farinha", "feijão", "grão-de-bico", "lentilhas",
  "pão", "quinoa",
  // Massas
  "esparguete", "fettuccine", "lasanha", "massa", "penne",
  // Carnes & enchidos
  "bifes", "carne de vaca", "carne picada", "chouriço", "coelho", "febras",
  "frango", "pancetta", "peru", "porco", "presunto", "salsichas",
  // Peixe & marisco
  "atum", "bacalhau", "camarão", "lulas", "marisco", "mexilhões", "peixe",
  "polvo", "salmão", "sardinhas",
  // Laticínios & ovos
  "feta", "iogurte", "leite", "manteiga", "mozzarella", "natas", "ovos",
  "parmesão", "pecorino", "queijo", "ricotta",
  // Ervas, especiarias & temperos
  "açafrão", "alecrim", "canela", "caril", "coentros", "cominhos", "curcuma",
  "gengibre", "louro", "malagueta", "manjericão", "mostarda", "noz-moscada",
  "orégãos", "paprika", "pimenta", "piripiri", "salsa", "tomilho",
  // Molhos & condimentos
  "ketchup", "maionese", "mel", "molho de soja", "óleo de sésamo", "tahini",
  "vinagre", "vinho", "azeite", "açúcar",
  // Frutos secos & sementes
  "amêndoa", "amendoim", "avelã", "castanhas", "nozes", "sementes de sésamo",
];

// Método de confeção por receita — usado para filtrar na aba Receitas.
// Valores: "airfryer" | "microondas" | "forno" | "fogao" | "sem"
window.METODOS = {
  // Peixe
  sardinhas: "forno", caldeirada: "fogao", "salada-salmao": "sem",
  "salmao-teriyaki": "airfryer", "salmao-forno": "forno", "empadao-peixe": "forno",
  paella: "fogao", "atum-nicoise": "fogao",
  // Frango
  "frango-piripiri": "airfryer", "frango-basco": "fogao", "cuscuz-frango": "fogao",
  "arroz-frango-chourico": "fogao", "frango-teriyaki": "forno",
  // Carne
  prego: "fogao", febras: "airfryer", strogonoff: "fogao",
  "vaca-brocolos": "fogao", moussaka: "forno",
  // Massas
  carbonara: "fogao", bolonhesa: "fogao", lasanha: "forno",
  fettuccine: "fogao", arrabiata: "fogao",
  // Vegetariano
  tortilha: "microondas", shakshuka: "microondas", "chili-vegetariano": "fogao",
  falafel: "airfryer", ratatouille: "forno", "fajitas-grao": "fogao",
  "lentilhas-abobora": "fogao", dal: "fogao", "feijao-curry": "fogao",
  rotolo: "forno", "batatas-bravas": "airfryer", "salada-massa": "fogao",
  // Sobremesas & pequeno-almoço
  "pasteis-nata": "forno", crumble: "forno", "bolo-cenoura": "forno",
  "panquecas-banana": "microondas",
  // Marisco
  "empanadas-camarao": "forno",
};

window.METODO_LABELS = {
  airfryer: { label: "Airfryer", emoji: "🌪️" },
  microondas: { label: "Microondas", emoji: "⚡" },
  forno: { label: "Forno", emoji: "🔥" },
  fogao: { label: "Fogão", emoji: "🍳" },
  sem: { label: "Sem cozedura", emoji: "🥗" },
};

window.RECIPES = [
  // ---------- Peixe ----------
  {
    id: "sardinhas", nome: "Sardinhas assadas", nomeOrig: "Grilled Portuguese sardines",
    categoria: "Peixe", tempo: 25, preco: 3.5, alergenios: ["peixe"],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/lpd4wy1614347943.jpg",
    dica: "Serve com batata cozida e salada de pimentos assados.",
    ingredientes: [
      { nome: "Sardinhas frescas", qtd: "600 g" },
      { nome: "Sal grosso", qtd: "q.b." },
      { nome: "Azeite", qtd: "2 c. sopa" },
      { nome: "Limão", qtd: "1 unidade" },
      { nome: "Batatas", qtd: "400 g" },
      { nome: "Pimentos", qtd: "2 unidades" },
    ],
  },
  {
    id: "caldeirada", nome: "Caldeirada de peixe", nomeOrig: "Portuguese fish stew",
    categoria: "Peixe", tempo: 45, preco: 4.0, alergenios: ["peixe", "marisco"],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/do7zps1614349775.jpg",
    dica: "Fica ainda melhor no dia seguinte.",
    ingredientes: [
      { nome: "Peixe variado", qtd: "500 g" },
      { nome: "Batatas", qtd: "500 g" },
      { nome: "Tomate maduro", qtd: "3 unidades" },
      { nome: "Cebola", qtd: "2 unidades" },
      { nome: "Pimento", qtd: "1 unidade" },
      { nome: "Azeite", qtd: "4 c. sopa" },
    ],
  },
  {
    id: "salada-salmao", nome: "Salada de salmão e abacate", nomeOrig: "Salmon avocado salad",
    categoria: "Peixe", tempo: 15, preco: 4.0, alergenios: ["peixe"],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/1549542994.jpg",
    dica: "Usa salmão fumado para uma versão ainda mais rápida.",
    ingredientes: [
      { nome: "Salmão", qtd: "200 g" },
      { nome: "Abacate", qtd: "1 unidade" },
      { nome: "Alface", qtd: "1 unidade" },
      { nome: "Pepino", qtd: "1/2 unidade" },
      { nome: "Limão", qtd: "1 unidade" },
      { nome: "Azeite", qtd: "2 c. sopa" },
    ],
  },
  {
    id: "salmao-teriyaki", nome: "Salmão teriyaki", nomeOrig: "Honey teriyaki salmon",
    categoria: "Peixe", tempo: 20, preco: 4.5, alergenios: ["peixe", "soja"],
    lojas: ["continente", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/xxyupu1468262513.jpg",
    dica: "Acompanha com arroz branco.",
    ingredientes: [
      { nome: "Lombos de salmão", qtd: "300 g" },
      { nome: "Molho de soja", qtd: "3 c. sopa" },
      { nome: "Mel", qtd: "2 c. sopa" },
      { nome: "Alho", qtd: "2 dentes" },
      { nome: "Gengibre", qtd: "1 colher" },
    ],
  },
  {
    id: "salmao-forno", nome: "Salmão no forno com funcho", nomeOrig: "Baked salmon with fennel & tomatoes",
    categoria: "Peixe", tempo: 30, preco: 4.0, alergenios: ["peixe"],
    lojas: ["continente", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/1548772327.jpg",
    dica: "Prato único: coloca batatas em rodelas por baixo do peixe.",
    ingredientes: [
      { nome: "Salmão", qtd: "400 g" },
      { nome: "Funcho", qtd: "1 bolbo" },
      { nome: "Tomate cereja", qtd: "200 g" },
      { nome: "Azeite", qtd: "2 c. sopa" },
      { nome: "Limão", qtd: "1 unidade" },
    ],
  },
  {
    id: "empadao-peixe", nome: "Empadão de peixe", nomeOrig: "Fish pie",
    categoria: "Peixe", tempo: 45, preco: 3.0, alergenios: ["peixe", "lactose", "gluten"],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/ysxwuq1487323065.jpg",
    dica: "Ótimo para aproveitar sobras de peixe cozido.",
    ingredientes: [
      { nome: "Peixe branco", qtd: "400 g" },
      { nome: "Batatas", qtd: "600 g" },
      { nome: "Leite", qtd: "200 ml" },
      { nome: "Manteiga", qtd: "2 c. sopa" },
      { nome: "Farinha", qtd: "2 c. sopa" },
      { nome: "Ervilhas", qtd: "100 g" },
    ],
  },
  {
    id: "paella", nome: "Paella", nomeOrig: "Paella",
    categoria: "Peixe", tempo: 50, preco: 4.5, alergenios: ["marisco", "peixe"],
    lojas: ["continente", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/9bl20p1763248192.jpg",
    dica: "Usa arroz carolino para um resultado mais cremoso.",
    ingredientes: [
      { nome: "Arroz carolino", qtd: "300 g" },
      { nome: "Camarão", qtd: "200 g" },
      { nome: "Lulas", qtd: "150 g" },
      { nome: "Mexilhões", qtd: "200 g" },
      { nome: "Pimento", qtd: "1 unidade" },
      { nome: "Açafrão", qtd: "1 pitada" },
    ],
  },
  {
    id: "atum-nicoise", nome: "Salada niçoise de atum", nomeOrig: "Tuna nicoise",
    categoria: "Peixe", tempo: 20, preco: 3.5, alergenios: ["peixe", "ovo"],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/yypwwq1511304979.jpg",
    dica: "Substitui as azeitonas por alcaparras, se preferires.",
    ingredientes: [
      { nome: "Atum em lata", qtd: "2 latas" },
      { nome: "Ovos", qtd: "2 unidades" },
      { nome: "Batatas", qtd: "300 g" },
      { nome: "Feijão verde", qtd: "150 g" },
      { nome: "Azeitonas", qtd: "50 g" },
      { nome: "Azeite", qtd: "2 c. sopa" },
    ],
  },

  // ---------- Frango ----------
  {
    id: "frango-piripiri", nome: "Frango piri-piri com salada", nomeOrig: "Piri-piri chicken and slaw",
    categoria: "Frango", tempo: 40, preco: 3.0, alergenios: [],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/hglsbl1614346998.jpg",
    dica: "Marina o frango na véspera para mais sabor.",
    ingredientes: [
      { nome: "Frango", qtd: "650 g" },
      { nome: "Piri-piri", qtd: "1 c. chá" },
      { nome: "Alho", qtd: "3 dentes" },
      { nome: "Limão", qtd: "1 unidade" },
      { nome: "Couve branca", qtd: "200 g" },
      { nome: "Cenoura", qtd: "1 unidade" },
    ],
  },
  {
    id: "frango-basco", nome: "Frango à basca", nomeOrig: "Chicken basquaise",
    categoria: "Frango", tempo: 40, preco: 3.0, alergenios: [],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/wruvqv1511880994.jpg",
    dica: "Serve com arroz branco ou pão rústico.",
    ingredientes: [
      { nome: "Coxas de frango", qtd: "700 g" },
      { nome: "Pimentos", qtd: "2 unidades" },
      { nome: "Tomate", qtd: "3 unidades" },
      { nome: "Cebola", qtd: "1 unidade" },
      { nome: "Vinho branco", qtd: "100 ml" },
      { nome: "Azeite", qtd: "2 c. sopa" },
    ],
  },
  {
    id: "cuscuz-frango", nome: "Cuscuz de frango", nomeOrig: "Chicken couscous",
    categoria: "Frango", tempo: 35, preco: 2.5, alergenios: ["gluten"],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/qxytrx1511304021.jpg",
    dica: "Hidrata o cuscuz com caldo quente, nunca a ferver em lume direto.",
    ingredientes: [
      { nome: "Cuscuz", qtd: "250 g" },
      { nome: "Frango", qtd: "300 g" },
      { nome: "Cenoura", qtd: "2 unidades" },
      { nome: "Grão-de-bico", qtd: "150 g" },
      { nome: "Cebola", qtd: "1 unidade" },
      { nome: "Cominhos", qtd: "1 c. chá" },
    ],
  },
  {
    id: "arroz-frango-chourico", nome: "Arroz de frango e chouriço", nomeOrig: "Chicken & chorizo rice pot",
    categoria: "Frango", tempo: 40, preco: 3.0, alergenios: [],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/fk80jp1763280767.jpg",
    dica: "Um clássico português de panela única.",
    ingredientes: [
      { nome: "Frango", qtd: "300 g" },
      { nome: "Chouriço", qtd: "100 g" },
      { nome: "Arroz", qtd: "250 g" },
      { nome: "Cebola", qtd: "1 unidade" },
      { nome: "Tomate", qtd: "2 unidades" },
      { nome: "Caldo de galinha", qtd: "600 ml" },
    ],
  },
  {
    id: "frango-teriyaki", nome: "Frango teriyaki gratinado", nomeOrig: "Teriyaki chicken casserole",
    categoria: "Frango", tempo: 40, preco: 3.0, alergenios: ["soja", "gluten"],
    lojas: ["continente", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg",
    dica: "Acompanha com arroz e brócolos salteados.",
    ingredientes: [
      { nome: "Peito de frango", qtd: "400 g" },
      { nome: "Molho de soja", qtd: "4 c. sopa" },
      { nome: "Mel", qtd: "2 c. sopa" },
      { nome: "Gengibre", qtd: "1 colher" },
      { nome: "Arroz", qtd: "250 g" },
    ],
  },

  // ---------- Carne ----------
  {
    id: "prego", nome: "Prego no pão com piripiri verde", nomeOrig: "Portuguese prego with green piri-piri",
    categoria: "Carne", tempo: 20, preco: 2.5, alergenios: ["gluten"],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/ewcikl1614348364.jpg",
    dica: "Bate os bifes finos e grelha-os em lume bem forte.",
    ingredientes: [
      { nome: "Bifes de vaca", qtd: "300 g" },
      { nome: "Pão de trigo", qtd: "2 unidades" },
      { nome: "Alho", qtd: "2 dentes" },
      { nome: "Azeite", qtd: "2 c. sopa" },
      { nome: "Piripiri", qtd: "q.b." },
      { nome: "Mostarda", qtd: "1 c. chá" },
    ],
  },
  {
    id: "febras", nome: "Febras assadas", nomeOrig: "Portuguese barbecued pork",
    categoria: "Carne", tempo: 30, preco: 3.0, alergenios: [],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/cybyue1614349443.jpg",
    dica: "Serve com batata frita ou arroz de tomate.",
    ingredientes: [
      { nome: "Febras de porco", qtd: "600 g" },
      { nome: "Alho", qtd: "4 dentes" },
      { nome: "Vinho branco", qtd: "50 ml" },
      { nome: "Louro", qtd: "2 folhas" },
      { nome: "Azeite", qtd: "3 c. sopa" },
      { nome: "Limão", qtd: "1 unidade" },
    ],
  },
  {
    id: "strogonoff", nome: "Strogonoff de vaca", nomeOrig: "Beef stroganoff",
    categoria: "Carne", tempo: 35, preco: 4.0, alergenios: ["lactose"],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/svprys1511176755.jpg",
    dica: "Usa natas à temperatura ambiente para não talhar.",
    ingredientes: [
      { nome: "Carne de vaca", qtd: "400 g" },
      { nome: "Cogumelos", qtd: "200 g" },
      { nome: "Natas", qtd: "200 ml" },
      { nome: "Cebola", qtd: "1 unidade" },
      { nome: "Mostarda", qtd: "1 c. sopa" },
      { nome: "Arroz", qtd: "250 g" },
    ],
  },
  {
    id: "vaca-brocolos", nome: "Vaca salteada com brócolos", nomeOrig: "Beef and broccoli stir-fry",
    categoria: "Carne", tempo: 20, preco: 4.0, alergenios: ["soja", "gluten"],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/m0p0j81765568742.jpg",
    dica: "Corta a carne contra o fio para ficar tenra.",
    ingredientes: [
      { nome: "Carne de vaca", qtd: "350 g" },
      { nome: "Brócolos", qtd: "300 g" },
      { nome: "Molho de soja", qtd: "3 c. sopa" },
      { nome: "Alho", qtd: "2 dentes" },
      { nome: "Óleo de sésamo", qtd: "1 c. chá" },
      { nome: "Arroz", qtd: "250 g" },
    ],
  },
  {
    id: "moussaka", nome: "Moussaka", nomeOrig: "Moussaka",
    categoria: "Carne", tempo: 60, preco: 3.5, alergenios: ["lactose"],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/ctg8jd1585563097.jpg",
    dica: "Deixa repousar 10 minutos antes de servir para cortar melhor.",
    ingredientes: [
      { nome: "Beringela", qtd: "2 unidades" },
      { nome: "Carne picada", qtd: "400 g" },
      { nome: "Tomate", qtd: "3 unidades" },
      { nome: "Cebola", qtd: "1 unidade" },
      { nome: "Molho bechamel", qtd: "300 ml" },
      { nome: "Queijo ralado", qtd: "50 g" },
    ],
  },

  // ---------- Massas ----------
  {
    id: "carbonara", nome: "Esparguete à carbonara", nomeOrig: "Spaghetti alla carbonara",
    categoria: "Massas", tempo: 20, preco: 2.5, alergenios: ["gluten", "ovo", "lactose"],
    lojas: ["continente", "pingoDoce"],
    foto: "https://www.themealdb.com/images/media/meals/llcbn01574260722.jpg",
    dica: "Mistura os ovos fora do lume para não cozinharem demais.",
    ingredientes: [
      { nome: "Esparguete", qtd: "300 g" },
      { nome: "Ovos", qtd: "3 unidades" },
      { nome: "Pancetta", qtd: "120 g" },
      { nome: "Queijo pecorino", qtd: "50 g" },
      { nome: "Pimenta preta", qtd: "q.b." },
    ],
  },
  {
    id: "bolonhesa", nome: "Esparguete à bolonhesa", nomeOrig: "Spaghetti bolognese",
    categoria: "Massas", tempo: 40, preco: 2.5, alergenios: ["gluten", "lactose"],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/sutysw1468247559.jpg",
    dica: "Quanto mais tempo o molho apurar, melhor.",
    ingredientes: [
      { nome: "Esparguete", qtd: "300 g" },
      { nome: "Carne picada", qtd: "400 g" },
      { nome: "Tomate", qtd: "400 g" },
      { nome: "Cenoura", qtd: "1 unidade" },
      { nome: "Cebola", qtd: "1 unidade" },
      { nome: "Queijo ralado", qtd: "40 g" },
    ],
  },
  {
    id: "lasanha", nome: "Lasanha", nomeOrig: "Lasagne",
    categoria: "Massas", tempo: 60, preco: 3.0, alergenios: ["gluten", "lactose"],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/wtsvxx1511296896.jpg",
    dica: "Usa placas frescas para não precisares de pré-cozer.",
    ingredientes: [
      { nome: "Placas de lasanha", qtd: "12 unidades" },
      { nome: "Carne picada", qtd: "400 g" },
      { nome: "Tomate", qtd: "400 g" },
      { nome: "Molho bechamel", qtd: "300 ml" },
      { nome: "Queijo ralado", qtd: "100 g" },
    ],
  },
  {
    id: "fettuccine", nome: "Fettuccine Alfredo", nomeOrig: "Fettuccine alfredo",
    categoria: "Massas", tempo: 20, preco: 2.5, alergenios: ["gluten", "lactose"],
    lojas: ["continente", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/0jv5gx1661040802.jpg",
    dica: "Junta um pouco da água da cozedura para o molho ficar cremoso.",
    ingredientes: [
      { nome: "Fettuccine", qtd: "300 g" },
      { nome: "Natas", qtd: "200 ml" },
      { nome: "Manteiga", qtd: "2 c. sopa" },
      { nome: "Parmesão", qtd: "60 g" },
      { nome: "Alho", qtd: "1 dente" },
    ],
  },
  {
    id: "arrabiata", nome: "Penne all'arrabbiata", nomeOrig: "Spicy arrabiata penne",
    categoria: "Massas", tempo: 20, preco: 1.5, alergenios: ["gluten"],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg",
    dica: "Simples, barato e pronto em 20 minutos.",
    ingredientes: [
      { nome: "Penne", qtd: "300 g" },
      { nome: "Tomate", qtd: "400 g" },
      { nome: "Alho", qtd: "3 dentes" },
      { nome: "Malagueta", qtd: "1 unidade" },
      { nome: "Azeite", qtd: "3 c. sopa" },
    ],
  },

  // ---------- Vegetariano ----------
  {
    id: "tortilha", nome: "Tortilha espanhola", nomeOrig: "Spanish tortilla",
    categoria: "Vegetariano", tempo: 35, preco: 1.5, alergenios: ["ovo"],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/quuxsx1511476154.jpg",
    dica: "Serve quente ou fria, cortada em quadrados.",
    ingredientes: [
      { nome: "Ovos", qtd: "6 unidades" },
      { nome: "Batatas", qtd: "600 g" },
      { nome: "Cebola", qtd: "1 unidade" },
      { nome: "Azeite", qtd: "150 ml" },
      { nome: "Sal", qtd: "q.b." },
    ],
  },
  {
    id: "shakshuka", nome: "Shakshuka", nomeOrig: "Shakshuka",
    categoria: "Vegetariano", tempo: 25, preco: 1.8, alergenios: ["ovo"],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/g373701551450225.jpg",
    dica: "Serve com pão para molhar no molho.",
    ingredientes: [
      { nome: "Ovos", qtd: "4 unidades" },
      { nome: "Tomate", qtd: "500 g" },
      { nome: "Pimento", qtd: "1 unidade" },
      { nome: "Cebola", qtd: "1 unidade" },
      { nome: "Cominhos", qtd: "1 c. chá" },
      { nome: "Azeite", qtd: "2 c. sopa" },
    ],
  },
  {
    id: "chili-vegetariano", nome: "Chili vegetariano", nomeOrig: "Vegetarian chilli",
    categoria: "Vegetariano", tempo: 35, preco: 1.8, alergenios: [],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/wqurxy1511453156.jpg",
    dica: "Congela muito bem — faz dose dupla.",
    ingredientes: [
      { nome: "Feijão vermelho", qtd: "400 g" },
      { nome: "Tomate", qtd: "400 g" },
      { nome: "Milho", qtd: "150 g" },
      { nome: "Cebola", qtd: "1 unidade" },
      { nome: "Pimento", qtd: "1 unidade" },
      { nome: "Cominhos", qtd: "1 c. chá" },
    ],
  },
  {
    id: "falafel", nome: "Falafel", nomeOrig: "Falafel",
    categoria: "Vegetariano", tempo: 30, preco: 1.5, alergenios: ["gluten", "sesamo"],
    lojas: ["continente", "pingoDoce"],
    foto: "https://www.themealdb.com/images/media/meals/u5e9qq1763795441.jpg",
    dica: "Serve em pão pita com salada e molho de tahini.",
    ingredientes: [
      { nome: "Grão-de-bico", qtd: "400 g" },
      { nome: "Cebola", qtd: "1 unidade" },
      { nome: "Salsa", qtd: "1 maço" },
      { nome: "Cominhos", qtd: "1 c. chá" },
      { nome: "Pão pita", qtd: "4 unidades" },
      { nome: "Tahini", qtd: "2 c. sopa" },
    ],
  },
  {
    id: "ratatouille", nome: "Ratatouille", nomeOrig: "Ratatouille",
    categoria: "Vegetariano", tempo: 40, preco: 2.0, alergenios: [],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/wrpwuu1511786491.jpg",
    dica: "Vegan, sem glúten e cheio de legumes.",
    ingredientes: [
      { nome: "Beringela", qtd: "1 unidade" },
      { nome: "Curgete", qtd: "1 unidade" },
      { nome: "Pimento", qtd: "1 unidade" },
      { nome: "Tomate", qtd: "4 unidades" },
      { nome: "Cebola", qtd: "1 unidade" },
      { nome: "Azeite", qtd: "3 c. sopa" },
    ],
  },
  {
    id: "fajitas-grao", nome: "Fajitas de grão-de-bico", nomeOrig: "Chickpea fajitas",
    categoria: "Vegetariano", tempo: 25, preco: 2.0, alergenios: ["gluten"],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/tvtxpq1511464705.jpg",
    dica: "Aquece as tortilhas numa frigideira seca.",
    ingredientes: [
      { nome: "Grão-de-bico", qtd: "400 g" },
      { nome: "Tortilhas de trigo", qtd: "4 unidades" },
      { nome: "Pimento", qtd: "2 unidades" },
      { nome: "Cebola", qtd: "1 unidade" },
      { nome: "Paprika", qtd: "1 c. chá" },
    ],
  },
  {
    id: "lentilhas-abobora", nome: "Chili de lentilhas e abóbora", nomeOrig: "Smoky lentil chili with squash",
    categoria: "Vegetariano", tempo: 35, preco: 1.8, alergenios: [],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/uwxqwy1483389553.jpg",
    dica: "Perfeito para os dias frios.",
    ingredientes: [
      { nome: "Lentilhas", qtd: "250 g" },
      { nome: "Abóbora", qtd: "300 g" },
      { nome: "Tomate", qtd: "400 g" },
      { nome: "Cebola", qtd: "1 unidade" },
      { nome: "Paprika fumada", qtd: "1 c. chá" },
    ],
  },
  {
    id: "dal", nome: "Caril de lentilhas", nomeOrig: "Dal fry",
    categoria: "Vegetariano", tempo: 30, preco: 1.5, alergenios: [],
    lojas: ["pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg",
    dica: "Serve com arroz basmati.",
    ingredientes: [
      { nome: "Lentilhas", qtd: "300 g" },
      { nome: "Tomate", qtd: "2 unidades" },
      { nome: "Cebola", qtd: "1 unidade" },
      { nome: "Curcuma", qtd: "1 c. chá" },
      { nome: "Gengibre", qtd: "1 colher" },
    ],
  },
  {
    id: "feijao-curry", nome: "Caril de feijão", nomeOrig: "Kidney bean curry",
    categoria: "Vegetariano", tempo: 30, preco: 1.5, alergenios: [],
    lojas: ["continente", "pingoDoce"],
    foto: "https://www.themealdb.com/images/media/meals/sywrsu1511463066.jpg",
    dica: "Usa feijão de lata para acelerar.",
    ingredientes: [
      { nome: "Feijão encarnado", qtd: "400 g" },
      { nome: "Tomate", qtd: "400 g" },
      { nome: "Cebola", qtd: "1 unidade" },
      { nome: "Garam masala", qtd: "1 c. chá" },
      { nome: "Arroz", qtd: "250 g" },
    ],
  },
  {
    id: "rotolo", nome: "Rotolo de cogumelos e castanhas", nomeOrig: "Mushroom & chestnut rotolo",
    categoria: "Vegetariano", tempo: 60, preco: 3.0, alergenios: ["lactose", "gluten", "frutosSecos"],
    lojas: ["continente", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/ssyqwr1511451678.jpg",
    dica: "Prato de festa, mas simples de montar.",
    ingredientes: [
      { nome: "Placas de lasanha", qtd: "6 unidades" },
      { nome: "Cogumelos", qtd: "300 g" },
      { nome: "Castanhas", qtd: "100 g" },
      { nome: "Espinafres", qtd: "200 g" },
      { nome: "Ricotta", qtd: "250 g" },
      { nome: "Queijo ralado", qtd: "50 g" },
    ],
  },
  {
    id: "batatas-bravas", nome: "Patatas bravas", nomeOrig: "Patatas bravas",
    categoria: "Vegetariano", tempo: 35, preco: 1.5, alergenios: [],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/bvg8sn1763298713.jpg",
    dica: "Ótimo petisco para partilhar.",
    ingredientes: [
      { nome: "Batatas", qtd: "600 g" },
      { nome: "Tomate", qtd: "300 g" },
      { nome: "Alho", qtd: "2 dentes" },
      { nome: "Paprika", qtd: "1 c. chá" },
      { nome: "Azeite", qtd: "3 c. sopa" },
    ],
  },
  {
    id: "salada-massa", nome: "Salada de massa mediterrânica", nomeOrig: "Mediterranean pasta salad",
    categoria: "Vegetariano", tempo: 20, preco: 1.8, alergenios: ["gluten"],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/wvqpwt1468339226.jpg",
    dica: "Ótima para marmita fria.",
    ingredientes: [
      { nome: "Massa fusilli", qtd: "300 g" },
      { nome: "Tomate cereja", qtd: "200 g" },
      { nome: "Azeitonas", qtd: "80 g" },
      { nome: "Queijo feta", qtd: "100 g" },
      { nome: "Azeite", qtd: "3 c. sopa" },
    ],
  },

  // ---------- Sobremesas & pequeno-almoço ----------
  {
    id: "pasteis-nata", nome: "Pastéis de nata", nomeOrig: "Portuguese custard tarts",
    categoria: "Sobremesa", tempo: 45, preco: 0.8, alergenios: ["lactose", "gluten", "ovo"],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/vmz7gl1614350221.jpg",
    dica: "Polvilha com canela antes de servir.",
    ingredientes: [
      { nome: "Massa folhada", qtd: "1 rolo" },
      { nome: "Leite", qtd: "300 ml" },
      { nome: "Açúcar", qtd: "200 g" },
      { nome: "Gemas", qtd: "4 unidades" },
      { nome: "Farinha", qtd: "2 c. sopa" },
      { nome: "Canela", qtd: "q.b." },
    ],
  },
  {
    id: "crumble", nome: "Crumble de maçã", nomeOrig: "Apple & blackberry crumble",
    categoria: "Sobremesa", tempo: 40, preco: 1.2, alergenios: ["lactose", "gluten"],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/xvsurr1511719182.jpg",
    dica: "Serve morno com uma bola de gelado.",
    ingredientes: [
      { nome: "Maçãs", qtd: "4 unidades" },
      { nome: "Farinha", qtd: "150 g" },
      { nome: "Manteiga", qtd: "100 g" },
      { nome: "Açúcar", qtd: "100 g" },
      { nome: "Canela", qtd: "1 c. chá" },
    ],
  },
  {
    id: "bolo-cenoura", nome: "Bolo de cenoura", nomeOrig: "Carrot cake",
    categoria: "Sobremesa", tempo: 60, preco: 1.5, alergenios: ["lactose", "gluten", "ovo", "frutosSecos"],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/vrspxv1511722107.jpg",
    dica: "Dura vários dias numa caixa fechada.",
    ingredientes: [
      { nome: "Cenoura", qtd: "300 g" },
      { nome: "Farinha", qtd: "200 g" },
      { nome: "Açúcar", qtd: "180 g" },
      { nome: "Ovos", qtd: "3 unidades" },
      { nome: "Nozes", qtd: "80 g" },
      { nome: "Óleo", qtd: "150 ml" },
    ],
  },
  {
    id: "panquecas-banana", nome: "Panquecas de banana", nomeOrig: "Banana pancakes",
    categoria: "Pequeno-almoço", tempo: 15, preco: 1.2, alergenios: ["ovo", "lactose", "gluten"],
    lojas: ["continente", "pingoDoce", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/sywswr1511383814.jpg",
    dica: "Com mel ou frutos vermelhos por cima.",
    ingredientes: [
      { nome: "Bananas", qtd: "2 unidades" },
      { nome: "Farinha", qtd: "150 g" },
      { nome: "Leite", qtd: "150 ml" },
      { nome: "Ovos", qtd: "2 unidades" },
      { nome: "Fermento", qtd: "1 c. chá" },
    ],
  },

  // ---------- Marisco ----------
  {
    id: "empanadas-camarao", nome: "Empanadas de camarão e cebolinho", nomeOrig: "Spring onion and prawn empanadas",
    categoria: "Marisco", tempo: 40, preco: 3.0, alergenios: ["gluten", "marisco"],
    lojas: ["continente", "mercadona"],
    foto: "https://www.themealdb.com/images/media/meals/1c5oso1614347493.jpg",
    dica: "Podes assar no forno em vez de fritar.",
    ingredientes: [
      { nome: "Camarão", qtd: "300 g" },
      { nome: "Massa quebrada", qtd: "2 rolos" },
      { nome: "Cebolinho", qtd: "1 maço" },
      { nome: "Alho", qtd: "2 dentes" },
      { nome: "Ovo (pincelar)", qtd: "1 unidade" },
    ],
  },
];
